- name: ensure {{ INSTALLATION_FOLDER }}/phpmyadmin/ directory exists
  file:
    path: '{{ INSTALLATION_FOLDER }}/phpmyadmin/'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: copy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: '{{ INSTALLATION_FOLDER }}/phpmyadmin/docker-compose.yml'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: template .env to {{ INSTALLATION_FOLDER }}/phpmyadmin/.env
  ansible.builtin.template:
    src: .env.j2
    dest: '{{ INSTALLATION_FOLDER }}/phpmyadmin/.env'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: docker-compose up -d in {{ INSTALLATION_FOLDER }}/phpmyadmin/
  shell: docker-compose --env-file .env up -d
  args:
    chdir: '{{ INSTALLATION_FOLDER }}/phpmyadmin/'