---
# add user to docker group
- name: add {{ ansible_user }} with a bash shell, to'docker' groups
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    shell: /bin/bash
    groups: docker
    append: yes

# config service to start on restart
- name: Enable service docker, and not touch the state
  ansible.builtin.service:
    name: docker
    enabled: yes