---
- name: Ensure older version of docker docker-engine docker.io containerd runc are removed
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  loop:
     - docker
     - docker-engine
     - containerd
     - runc

- name: Ensure apt-transport-https, ca-certificates, curl, gnupg and lsb-release are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
     - apt-transport-https
     - ca-certificates
     - curl
     - gnupg
     - lsb-release

- name: add docker ubuntu gpg
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Execute the command in remote shell add repository
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Ensure docker-ce, docker-ce-cli and containerd.io are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
     - docker-ce 
     - docker-ce-cli 
     - containerd.io