---
- name: Add the user 'dpwanjala' with a specific uid and a primary groups of 'admin,sudo'
  ansible.builtin.user:
    name: dpwanjala
    comment: David Wanjala
    uid: 1040
    state: present
    groups: admin,sudo
    append: yes
  ignore_errors: true

- name: Create a 2048-bit SSH key for user dpwanjala in ~dpwanjala/.ssh/id_rsa
  ansible.builtin.user:
    name: dpwanjala
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


# copy authorized_keys from root user to currently created user to allow to connect with ssh
- name: copy authorized_keys from root user to currently created user to allow to connect with ssh
  shell: cp -v /root/.ssh/authorized_keys /home/dpwanjala/.ssh/authorized_keys && chown dpwanjala:dpwanjala /home/dpwanjala/.ssh/authorized_keys
  ignore_errors: true

- name: Activate passwordless commands for users in sudo group and validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo ALL=(ALL) NOPASSWD: ALL'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s