---
- name:  download the current stable release of Docker Compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  become: yes
  ignore_errors: true

- name: apply executable permissions to the docker compose binary
  shell: chmod +x /usr/local/bin/docker-compose
  become: yes
  ignore_errors: true

 
