- name: ensure /srv/traefik/ directory exists
  file:
    path: /srv/traefik/
    state: directory
    owner: '{{ USER }}'
    group: '{{ USER }}'

- name: copy docker-compose.yml to traefik directory
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /srv/traefik/docker-compose.yml
    owner: '{{ USER }}'
    group: '{{ USER }}'

- name: ensure docker web network is created
  shell: docker network create web
  ignore_errors: true

- name: template .env to traefik folder
  ansible.builtin.template:
    src: .env.j2
    dest: /srv/traefik/.env
    owner: '{{ USER }}'
    group: '{{ USER }}'

- name: run docker-compose up -d with .env in traefik folder
  shell: docker-compose --env-file /srv/traefik/.env up -d
  args:
    chdir: /srv/traefik/